# fly.toml app configuration file generated for car-search-ai on 2023-06-04T20:08:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "car-search-ai"
primary_region = "dfw"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
